# configuration for "master" branch
-
  configuration: Release
  branches:
      only:
        - master
  version: 1.0.{build}
  environment:
    GITHUB_USERNAME:
      secure: 0Q9MvUId56SizmZwCf0cgg==
    GITHUB_TOKEN:
      secure: R3xA9iMXfUUtFd3wuL38pcDa0/BjjpBvNcGShr5LRibZtBoOVSH47Jat75rwaGur
    NUGET_SOURCE: https://www.nuget.org/api/v2/package
    NUGET_APIKEY:
      secure: 0g2AqQxgiAIFhqoJbbmEPrJa15Z8U5xYT6vQe43Gocuxbjw74hBAIKbU+Cj65UNd
  build_script:
  - ps: >-
      ./bootstrap.ps1

      ./build.cmd
  artifacts:
  - path: artifacts/*
  - path: '**/bin/*'
  test: off
  
# configuration for "develop" branch
-
  configuration: Development
  branches:
      except:
          - master
          
  version: 1.0.{build}
  environment:
    NUGET_SOURCE: https://www.myget.org/F/akavache/api/v2/package
    NUGET_APIKEY:
      secure: YP/3KxC2ffsuHNaolPXj66JVGzSjON9FcR2S2OEzn9c6SV14oPzUh1ySyeT+G+aA
  build_script:
  - ps: >-
      ./bootstrap.ps1

      ./build.cmd
  artifacts:
  - path: artifacts/*
  - path: '**/bin/*'
  test: off

# "fall back" configuration for all other branches
# no "branches" section defined
# do not deploy at all
-
  configuration: Development